### ISSUE TITLE
Wrong MODEL_TAG value in README

### ISSUE THREAD

**Issue by offchan42** [runpod-workers/worker-stable_diffusion_v1#8]
Notice the `MODEL_TAG` value in this command:
https://github.com/runpod-workers/worker-stable_diffusion_v1/blob/773b2f2bee14b0476ca29207d99e899cd3b57364/README.md?plain=1#L23

It's set to `main` but it should be `runwayml/stable-diffusion-v1-5` according to this line of code: https://github.com/runpod-workers/worker-stable_diffusion_v1/blob/773b2f2bee14b0476ca29207d99e899cd3b57364/src/rp_handler.py#L76

**Comment by justinmerrell** [comment]
Correct, fixed, thank you!
